# Generated by Django 5.0.7 on 2024-07-29 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('orderdata', 'Order Data'), ('productdata', 'Product Data'), ('logistic', 'Logistic'), ('marketing', 'Marketing')], max_length=20)),
                ('file', models.FileField(upload_to='data_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=10, unique=True)),
                ('store_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CSVFile',
        ),
        migrations.AddField(
            model_name='datafile',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parserapp.store'),
        ),
    ]
